// Investigate assets. Execute continuity. Duevia remains an always-on investigation agent. Five agent capabilities now converge on failover.
const workflow = [
  ["01", "Heartbeat", "Servicers sign a compact asset-state update on a defined SLA."],
  ["02", "Protect", "When the heartbeat expires, X Layer pauses new issuance and pool deposits."],
  ["03", "Recover", "The AI agent reconstructs the latest state from encrypted snapshots and chain events."],
  ["04", "Handoff", "A human-approved successor publishes the recovery root and resumes operations."],
];

const customers = [
  ["Small RWA issuers", "Tokenized receivables and private-credit pools that cannot afford a bespoke backup-servicer stack."],
  ["Protocol operators", "Onchain lending and asset-pool teams that need a fail-safe when an offchain counterparty goes dark."],
  ["Successor servicers", "Approved operators who need a portable, verifiable starting point instead of a broken spreadsheet."],
];

export default function Home() {
  return <main className="marketing-page">
    <nav className="site-nav shell"><a className="xray-brand" href="#top" aria-label="Duevia RWA home"><span className="xray-mark">D</span><span>DUEVIA RWA</span></a><div className="site-links"><a href="#problem">Problem</a><a href="#protocol">Protocol</a><a href="#customers">Customers</a></div><a className="nav-cta" href="/app">Open Continuity Agent <span>→</span></a></nav>

    <section className="xray-hero shell continuity-marketing-hero" id="top"><div className="hero-grid-line line-a" /><div className="hero-grid-line line-b" /><div className="xray-kicker"><i /> AI AGENT · RWA CONTINUITY · X LAYER</div><h1>When a servicer<br />goes dark, assets<br /><em>stay alive.</em></h1><div className="hero-bottom"><p>Duevia is an AI failover layer for tokenized receivables and private credit. It reconstructs asset state after an offchain service interruption, pauses unsafe actions, and hands operations to an authorized successor on X Layer.</p><div className="hero-buttons"><a className="button-dark" href="/app">Run the outage demo <span>→</span></a><a className="button-quiet" href="#problem">Why this matters</a></div></div><div className="hero-proof-bar"><div><b>Detect</b><span>Heartbeat SLA expires</span></div><div><b>Protect</b><span>Pause unsafe pool actions</span></div><div><b>Recover</b><span>AI rebuilds asset state</span></div><div><b>Resume</b><span>Successor attests on X Layer</span></div></div></section>

    <section className="problem-section" id="problem"><div className="shell problem-grid"><div><span className="section-index">THE FAILURE MODE / 01</span><h2>RWA tokens can remain live after the team behind them disappears.</h2></div><div className="problem-copy"><p>Tokenization moves ownership and settlement onchain, but servicing still depends on a company, a database, and a recurring report. If that service stops, investors cannot tell whether balances, repayments, or redemptions are still current.</p><p>Duevia treats missing service data as an operational event: protect the pool first, reconstruct the state second, and resume only after an authorized handoff.</p></div></div><div className="shell signal-rail" aria-label="Duevia continuity flow"><span>SERVICER OFFLINE</span><i>→</i><span>AI RECOVERY PLAN</span><i>→</i><span>X LAYER CIRCUIT BREAKER</span><i>→</i><span>SUCCESSOR HANDOFF</span></div></section>

    <section className="modules-section shell" id="protocol"><div className="section-heading-row"><div><span className="section-index">THE PROTOCOL / 02</span><h2>One failure.<br />Four controlled moves.</h2></div><p>AI handles messy evidence and missing context. Deterministic rules handle money. X Layer handles the state transition.</p></div><div className="module-list">{workflow.map(([number, title, copy]) => <article key={number}><span className="module-number">{number}</span><div><h3>{title}</h3><small>{title === "Recover" ? "AI reconstructs · human approves" : title === "Protect" ? "Contract-enforced" : "Signed evidence"}</small></div><p>{copy}</p><span className="module-arrow">→</span></article>)}</div></section>

    <section className="product-preview continuity-preview"><div className="shell preview-grid"><div className="preview-copy"><span className="section-index light">X LAYER EXECUTION / 03</span><h2>A recovery action,<br />not a PDF.</h2><p>When a servicer misses its SLA, Duevia can publish a new recovery attestation to a registry deployed on X Layer. The raw borrower data stays encrypted offchain; the pool receives a verifiable state and validity window.</p><a className="button-light" href="/app">Open the DApp <span>→</span></a></div><div className="report-mock continuity-mock" aria-label="Duevia Continuity Agent example"><div className="mock-top"><span>POOL / RCV-018</span><b>SERVICER OFFLINE</b></div><div className="mock-score"><strong>72h</strong><span>since last signed<br />service heartbeat</span></div><div className="mock-factors"><div><span>Pool action</span><b>PAUSED</b></div><div className="warn"><span>Recovery root</span><b>READY</b></div><div><span>Assets resolved</span><b>18 / 18</b></div><div><span>Chain</span><b>X LAYER</b></div></div><div className="mock-alert"><i>!</i><div><b>Primary servicer unavailable</b><span>New issuance remains blocked until a successor attests to the reconstructed state.</span></div></div><div className="mock-chain"><span className="x-mini">D</span><div><b>Failover state ready</b><small>Encrypted capsule · public recovery root</small></div><em>PAUSED → RESTORE</em></div></div></div></section>

    <section className="customers-section shell" id="customers"><div className="section-heading-row"><div><span className="section-index">WHO PAYS / 04</span><h2>For teams that cannot<br />afford a service outage.</h2></div></div><div className="customer-grid">{customers.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>

    <section className="final-cta"><div className="shell"><span>RWA CONTINUITY INFRASTRUCTURE</span><h2>Keep the asset<br />operable.</h2><a className="button-blue" href="/app">Launch Duevia <span>→</span></a></div></section><footer className="site-footer shell"><div className="xray-brand"><span className="xray-mark">D</span><span>DUEVIA RWA</span></div><p>AI failover infrastructure for tokenized private credit.</p><span>Built for X Layer AI Season · 2026</span></footer>
  </main>;
}
